### ISSUE TITLE
Add status effects to chassis

### ISSUE THREAD

**Issue by CptMoore** [BattletechModders/MechEngineer#112]
similar to critical hits

idea here is to allow quirks per chassis (more armor, faster speed, etc)

**Comment by LadyAlekto** [comment]
How about the tags that are already used for equipment, be possible to be used for the chassis itself too?

**Comment by CptMoore** [comment]
No, all tags have to be reimplemented to be used for chassis

**Comment by CptMoore** [comment]
added tag restrictions in d035bb1c5d91a7a16fdee9a4ef4aff2864cc0f73
