### ISSUE TITLE
string.Format on descriptions can lead to unhelpful errors.

### ISSUE THREAD

**Issue by m22spencer** [BattletechModders/MechEngineer#135]
https://github.com/BattletechModders/MechEngineer/blob/8fac34d84f2a7e6e81e78cd38bd83335f18c4aad/source/Features/Descriptions/BonusDescriptions.cs#L100

If a modder provides an invalid format index such as `{foo}`, they get back a nondescriptive error. 
Propose adding a try catch w/ output of the invalid format string.

**Comment by CptMoore** [comment]
> If a modder
You mean Lady? ;)

Im thinking about adding more descriptive stuff to all configration loops, ME has too many of those

**Comment by LadyAlekto** [comment]
i kind of feel personally attacked even though id love it would tell proper the eff up ;)
