### ISSUE TITLE
Missing engines in campaign

### ISSUE THREAD

**Issue by bozephalus** [BattletechModders/MechEngineer#141]
Hi,

sadly i have not found an entry for my issue - if i am starting a new campaing, all my mechs have no "Mech Engineer" related items in the center torso - no but the SHD-2H.

But even there i am not able to move an 11th HS into to the core, for there is no room on the 275er engine ... .
I guess something went wrong and tried it again with clean install ... and a 2nd time to be sure, I think i might have missed something but i have no clue what it is.

Appretiate your help.

**Comment by CptMoore** [comment]
we are in the process of changing the way things are loaded into mechs, I'd stay away until the next MechEngineer version comes out.

nevertheless, HS can't be moved onto the core anymore, they are now part of the E-Cooling item.

**Comment by bozephalus** [comment]
OK Thanks for your fast response - i will wait for the next version then.

**Comment by CptMoore** [comment]
well the newest versions should all be stable in this regard, just reopen if you have the same issue.. and if you do please post the mod list here, probably some incompatibility.
