### ISSUE TITLE
Defense Gyro not providing stability

### ISSUE THREAD

**Issue by Vesparco** [BattletechModders/MechEngineer#142]
I assume is already traced but just in case it is not. The defensive gyros do not provide stability within the vainilla version of mechengineer.

This provides inestability to both player and ia mechs during combat when hit.

**Comment by CptMoore** [comment]
oh thx, I didnt realize but Im anyway revising critical hits. gyro providing stability was a workaround to having no critical effects for destroyed components. I'm in the process of adding that, so there is always a base stability and a destroyed gyro just removes that stability.

**Comment by CptMoore** [comment]
stability threshold is now set to 0 using critical effects, hopefully this works for all gyros thx to custom defaults
