### ISSUE TITLE
V1.1.9 head slots

### ISSUE THREAD

**Issue by crystoph74** [BattletechModders/MechEngineer#147]
![WHM-6r error message](https://user-images.githubusercontent.com/48889838/54883684-8a7e9080-4e3e-11e9-8512-d828e9af2890.JPG)
![WHM-6r head slots](https://user-images.githubusercontent.com/48889838/54883685-8a7e9080-4e3e-11e9-8168-fb59c7702076.JPG)
 
Cant Remove them andmost other non modded mech have the same issue

**Comment by CptMoore** [comment]
looks like a mod that adds mechs which dont have the head adjusted to 6, and had another head slot size than vanilla.

Known mod combinations that work:
- Vanilla+ME
- RT (includes ME)
- XLRP+ME (that is the one I use for playtesting now)

there exists also an ME patch for JK_Variants, but dont know if thats up-to-date

**Comment by crystoph74** [comment]
the normal mech are doing it to the blackjack vindicator starter are doing ut to a increased the head slot by changing your setting and was able to put a sldf cockpit which took up the cockpit and 2nd life support and sensor slot

**Comment by CptMoore** [comment]
is this now still an issue, since you could mod ME yourself?

**Comment by Kurotabo047** [comment]
I'm having the same issue with a lot of modded mechs, such as the Sun Spider and Night Gyr off of the Battletech Nexus. Same issue with the slots of the right arm. Is there a way to remove the slot limitations?
![Augh](https://user-images.githubusercontent.com/49536470/55991138-85f80b80-5c77-11e9-87c3-9b78e820fcd8.png)

**Comment by CptMoore** [comment]
I'll close this, if there are issues with other mods, you can still post those issues here
