### ISSUE TITLE
I m not sure where to finde new gear ( ferro-fibrous armor endo steel structure, XL engines, other interesting gear) 

### ISSUE THREAD

**Issue by st3fan21** [BattletechModders/MechEngineer#148]
Hello,

I finished the story once and now i am doing an ironman run, with the mech engineer mod. 

I tryed Rougetech and i loved the design of the mechbay and how u can choose engines and other gear but i relly didn t like the gameplay, as it was already time consuming in vanilla and now it was harder and slower.

I am halfway through the campaign and i did not find a DHS kit or XL engine, ferro-fibrous armor, endo steel structure or other items.

can these be found in shops or salvage?

**Comment by CptMoore** [comment]
We never had time to fully implement a nice shop system for those exotic things, so we settled on having them preinstalled and not removable on some of the SLDF mechs.

If you want a nice mod that makes it much better, install the [XLRP](https://www.nexusmods.com/battletech/mods/339) mod.

**Comment by st3fan21** [comment]
Thanks, I will try it right now, can't wait to see how it works.

Btw thanks for all ur work on mods for this game :D

**Comment by st3fan21** [comment]
installed XLRP and so far it s exactly what i wanted, and i can also see LBX cannons, i loved those in mechwarrior games. 

I can not find anywhere the details of what happens when i destroy LIFE SUPPORT (head mounted system) on a planet without atmosphere (mars, lunar or others)?

**Comment by CptMoore** [comment]
life support prevents overheated mechs in damaging pilots

there is no logic built that somehow takes the atmosphere into account, it is assumed that the oxygen in the mech is sufficient for the battle

**Comment by st3fan21** [comment]
Seems pretty well thought.
Overall an Interesting system, so i gather for every overheat the pilot looses 1 health?

Btw, i did not find this in any changelog of any mods (Mechengineer or XLRP.)

Where should i find info like this?

**Comment by CptMoore** [comment]
> for every overheat the pilot looses 1 health?

yea

> Where should i find info like this?

you can find an outdated readme on the [main page](https://github.com/BattletechModders/MechEngineer#shutdowninjuryprotection)

but all the details are in the code, so kinda hard to know everything

**Comment by st3fan21** [comment]
hey sry to bother u but how do cockpit SLIC and beagle active probes work in this mod. 
Normally in mechwarrior / mechcommander they gave benefits to only the mech they were installed (BAP).  But either they are not working on my mechs at all or they are increasing all of the mechs sensors and presumambly visual range.

I can not really check the visual range but the sensor i checked and it s the same for all my mechs and two of them have both SLIC and BAP.

And also do they work cumulatively like:  BAP 15% +SLIC 20% =35% sensor increase?

**Comment by st3fan21** [comment]
Btw, i can confirm that SLIC + COMMS system +4 cumulate the morale boost. But in a weird way.

I know COMMs systems do not cumulate.

I have max morale 35 + 4(COMMS) + (2xSLIC) = 42

Should be 41, but one of the SLICs is on the HIGHLANDER 732B SLDF and can not be removed, maybe thats why.

**Comment by CptMoore** [comment]
BAP is not part of mechengineer, maybe the lowvis mod properly implements it.

The SLIC was given 20% sensor range increase just to give the SLDF mechs something. (it was a copy from RT mod anyway).

The morale boot increment is something that I dont really know how it works.

**Comment by CptMoore** [comment]
> And also do they work cumulatively like: BAP 15% +SLIC 20% =35% sensor increase?

its probably multiplicative, at least the SLIC is.. so 1 * 1.15 * 1.20 = 1.38

**Comment by Ruffyen** [comment]
Sorry to hijack this tread but I was trying to add a heatsink to a 275 core (which says you can put one internally), but everyplace I tried to drag the heat sink ended up externally taking a spot in the center torso.

What am I missing?

**Comment by CptMoore** [comment]
@Ruffyen there are special "E-Cooling" items you need to install... for one more heatsink you need "E-Cooling +1"

in lore, "engine external" and "engine internal" heat sinks are completely different, so you can't just dragn drop heatsinks anymore (and there were technical incompatibilities with other mods)

**Comment by vengefire** [comment]
> We never had time to fully implement a nice shop system for those exotic things, so we settled on having them preinstalled and not removable on some of the SLDF mechs.
> 
> If you want a nice mod that makes it much better, install the [XLRP](https://www.nexusmods.com/battletech/mods/339) mod.

Hi CptMoore,

I recently configured XLRP and asked the same question as the OP. I'm aware you can come across the components in stores, but I'm interested in attempting to replicate the behavior of RT several iterations ago where if you carefully force the pilot of a 'mech with a DHS engine, for example, to eject you could recover the internal component.

AdjustedMechRecovery and AdjustedMechSalvage basically turns these toys from rare to urban legend status.

Let's ignore the realism aspect for the moment of having an internal component drop separate to it's housing component :-) 

This was at one point something you could do, and it is no longer. Digging into the configuration of ME, I see the no_salvage flag has been applied to the armor, structure, and cooling categories.

From the cursory digging I've done, I'm relatively certain removing the no_salvage flag will re-enable the previous behavior I desire, however I would like to know:
1 - Can you foresee any unexpected side effects to making said change.
2 - Will the the components be _installable_ once obtained via this method. I realize this might seem like a stupid question, and I'm 99% certain they will be as they should be duplicate instances of items acquired via the store, but it doesn't hurt to ask before I waste my time setting up a mod to overwrite the categories in question.

Thanks mate.

**Comment by st3fan21** [comment]
If u re really looking for these items i ve found some:
I have bought 3 DHS systems and 5 DH sinks from the blackmarket, one or two sinks from normal stores. Also bought ferro fibrous armor. Did not ever find endo steel structure yet but i am taking a break from battletech until URBAN WARFARE.

In the blackmarket i also found 2 GAUSS GUNS one of them +++.

In short as soon as the pirates ask you to join u better either have friendly or better status or if not just be prepared to pay the entry fee cause it s worth it. 

If u find a way to make these items clearly salvageable let me  know but there is another issue:

I salvaged an SLDF Catapult and it has DHS system BUT it is not removable, just like the one mounted on the HIGHLANDER 732B SLDF you get in main campaign. Since both are not removable it stands to reason that u cant salvage them separately.

**Comment by CptMoore** [comment]
> 1 - Can you foresee any unexpected side effects to making said change.

Don't think so, removing no_salvage certainly should do the trick. Seems you have done more research than I and know more about this salvaging now (I only know that salvaging was integrated into CC)

> 2 - Will the the components be installable once obtained via this method

Yea! There are no special kits (anymore) which are preinstalled but can't be reinstalled. Kits just behave like any other component.

**Comment by st3fan21** [comment]
> BAP is not part of mechengineer, maybe the lowvis mod properly implements it.
> 
> The SLIC was given 20% sensor range increase just to give the SLDF mechs something. (it was a copy from RT mod anyway).
> 
> The morale boot increment is something that I dont really know how it works.

**Comment by st3fan21** [comment]
Sry i closed by accident, can u tell me where to modifi this salvaging setting? 

I want to test it also.



> > We never had time to fully implement a nice shop system for those exotic things, so we settled on having them preinstalled and not removable on some of the SLDF mechs.
> > If you want a nice mod that makes it much better, install the [XLRP](https://www.nexusmods.com/battletech/mods/339) mod.
> 
> Hi CptMoore,
> 
> I recently configured XLRP and asked the same question as the OP. I'm aware you can come across the components in stores, but I'm interested in attempting to replicate the behavior of RT several iterations ago where if you carefully force the pilot of a 'mech with a DHS engine, for example, to eject you could recover the internal component.
> 
> AdjustedMechRecovery and AdjustedMechSalvage basically turns these toys from rare to urban legend status.
> 
> Let's ignore the realism aspect for the moment of having an internal component drop separate to it's housing component :-)
> 
> This was at one point something you could do, and it is no longer. Digging into the configuration of ME, I see the no_salvage flag has been applied to the armor, structure, and cooling categories.
> 
> From the cursory digging I've done, I'm relatively certain removing the no_salvage flag will re-enable the previous behavior I desire, however I would like to know:
> 1 - Can you foresee any unexpected side effects to making said change.
> 2 - Will the the components be _installable_ once obtained via this method. I realize this might seem like a stupid question, and I'm 99% certain they will be as they should be duplicate instances of items acquired via the store, but it doesn't hurt to ask before I waste my time setting up a mod to overwrite the categories in question.
> 
> Thanks mate.

**Comment by Ruffyen** [comment]
I noticed in my games "output_log.txt" the following error keeps happening whenever I blow something up on an enemy mech:

MechEngineer [ERROR] COMPRESS DESTROYED    at MechEngineer.FloatieHandler.CompressFloatieMessages(BattleTech.FloatieMessage incoming, System.Collections.Generic.Queue`1 queue)

Is this some information you need to track, or should I just ignore it?
[output_log.txt](https://github.com/BattletechModders/MechEngineer/files/3144618/output_log.txt)

**Comment by CptMoore** [comment]
thats there in case you see an engine destroyed message on the screen, but the mech doesnt die.. then look at the last "ERROR" and send me the stacktrace.

**Comment by CptMoore** [comment]
I'll close this, just reopen or create new tickets for new issues or so
