### ISSUE TITLE
Question: Possible to use HardpointFix only?

### ISSUE THREAD

**Issue by clintonmead** [BattletechModders/MechEngineer#149]
Just a question, is it possible to use the HardpointFix mod only, i.e. the part of the that adjusts the hardpoints limitations to be based on what can be visually be displayed on the model, without any other of the mods changes? Is there a feature selected in some settings to do this?

**Comment by CptMoore** [comment]
unfortunately not, I had it as a standalone mod, but couldn't maintain it that way
I can try to improve the ME settings so one could disable all features individually and only keep HardpointFix (maybe its already possible but certainly its not user friendly)

**Comment by clintonmead** [comment]
Would hacking around with this loop:

```
                foreach (var feature in FeaturesList.Features)
                {
                    feature.SetupFeature();
                }
```

be good enough to do the job or does HardpointFix need dependencies to be loaded?

**Comment by CptMoore** [comment]
yea I started introducing the concept of "Feature" where I encapsulate / separate stuff in ME

if you just want it quickly for yourself then just removing all features from FeatureList.cs except HardpointFix should do it

to make is possible to do that using setings, I would still need to normalize all settings + make dependencies between features

each feature has a property called "Enabled" some features have that exposed to the settings, some have it hardcoded to "true". the latter thing is that I have to fix for all features and make sure one can disable features... but not if it is a dependency to other features.

**Comment by CptMoore** [comment]
I've updated ME to properly be configurable, so one could just disable all features
that version I'll release once UW is officially out

**Comment by CptMoore** [comment]
I've just released the new ME which allows to disable all features except the HardpointFix... if that won't work just reopen this ticket

**Comment by clintonmead** [comment]
Thanks for all your work. Looks largely good, below is the `settings.json` that I'm using, but I also had to manually delete the `data`, `StreamingAssets` and `advancedJsonMerge` folders. Unfortunately I'm not sure there's much you about this aside from splitting the mod as these folders are probably merged by ModTek before your code is even entered that examines the settings.

```
{
    "AccuracyEffects" : {
        "Enabled" : false,
    },
    "ArmActuator" : {
        "Enabled" : false,
    },
    "ArmorStructureChanges" : {
        "Enabled" : false,
    },
    "ArmorStructureRatio" : {
        "Enabled" : false,
    },
    "AutoFixer" : {
        "Enabled" : false,
    },
    "BattleTechLoadFix" : {
        "Enabled" : true,
    },
    "ComponentExplosions" : {
        "Enabled" : false,
    },
    "CompressFloatieMessages" : {
        "Enabled" : true,
    },
    "CriticalEffects" : {
        "Enabled" : false,
    },
    "DebugCycleCombatSounds" : {
        "Enabled" : false,
    },
    "DebugSaveMechToFile" : {
        "Enabled" : false,
    },
    "DynamicSlots" : {
        "Enabled" : false,
    },
    "Engine" : {
        "Enabled" : false,
    },
    "Globals" : {
        "Enabled" : false,
    },
    "HardpointFix" : {
        "Enabled" : true,
        "AutoFixChassisDefWeaponHardpointCounts" : true,
        "EnforceHardpointLimits" : true,
        "AllowDefaultLoadoutWeapons" : false,
    },
    "InvalidInventory" : {
        "Enabled" : false,
    },
    "LocationalEffects" : {
        "Enabled" : false,
    },
    "MechLabSlots" : {
        "Enabled" : false,
    },
    "MoveMultiplierStat" : {
        "Enabled" : false,
    },
    "NewSaveFolder" : {
        "Enabled" : false,
    },
    "OverrideDescriptions" : {
        "Enabled" : false,
    },
    "OverrideGhostVFX" : {
        "Enabled" : false,
    },
    "OverrideTonnage" : {
        "Enabled" : false,
    },
    "ShutdownInjuryProtection" : {
        "Enabled" : false,
    },
    "TurretLimitedAmmo" : {
        "Enabled" : false,
    },
    "TurretMechComponents" : {
        "Enabled" : false,
    }
}
```

**Comment by CptMoore** [comment]
Yep those folders need to be deleted, nothing i can do as you daid
