### ISSUE TITLE
Issue since 1.6 game patch

### ISSUE THREAD

**Issue by shadowfax13th** [BattletechModders/MechEngineer#150]
I'm more or less illiterate about this stuff, but I think from the little I can make out that either MechEngineer or Custom Components might be why I can't get the newly patched game to work with any Mech mods. I realize I probably have to wait for everything to be updated, but I'm just sharing what I found in the hopes that one or either of these two mods might be my issue.

Here's the games output log:
[output_log.txt](https://github.com/BattletechModders/MechEngineer/files/3259370/output_log.txt)
Here's the MechEngineer log:
[log.txt](https://github.com/BattletechModders/MechEngineer/files/3259371/log.txt)

**Comment by LadyAlekto** [comment]
You will need the new battletechperformancefix

issue is that pre 1.6 units dont have the ghost blip in their bundle

**Comment by shadowfax13th** [comment]
thanks so much, I've been going a little nuts trying to figure this out

**Comment by shadowfax13th** [comment]
Ok, LadyAlekto I owe you a great big thank you!
I would never have figured this out otherwise.
