### ISSUE TITLE
Additional issues

### ISSUE THREAD

**Issue by shadowfax13th** [BattletechModders/MechEngineer#151]
I'm not sure where this is coming from, but I also posted it on the Custom Components issues...

Rather than pulse lasers shooting three times, or UACs twice, the UACs dump all their damage in one shot and the pulse lasers are it seems only doing one shot with the damage one pulse would. Medium pulse for instance do 12 x 3 shots, but now it's one shot of 12.

**Comment by LadyAlekto** [comment]
Stop spamming mods with issues that have nothing to do with the mods

**Comment by shadowfax13th** [comment]
I don't use Rogue Tech, never have. And since it was only after starting to use MechEngineer that the clan weapons became part of battletech for me, I assumed it was part of the MechEngineer mod. As far as I can tell this isn't spamming. And since Custom Components is included in this, I posted there as well. 

If I'm mistaken, that's one thing.

**Comment by LadyAlekto** [comment]
MechEngineer does not have Clan Weapons

Custom Components has nothing to do with what you experience

That stuff is a completely different mod that was not updated to 1.6

So if you mod, you should at least understand what you are throwing together

This is like going to your mechanic because your houseplant grows weird

**Comment by shadowfax13th** [comment]
No, it really isn't
As far as I can tell the CC is for making custom components... like clan weapons, pulse and UACs for instance. And MechEngineer and CC are the only things I can figure are part of the issue. That said, it's quite possible I'm wrong. If that's the case I apologize to the author and will leave it at that. 
All it would have taken is a simple, this isn't the mod you're looking for, and I would have gone back to trying to figure what went wrong after the update. So, thanks for that.

**Comment by LadyAlekto** [comment]
Yeah, no

Absolutely No it doesnt

As i said, you should at least understand WHAT you are using

For things like multishot weapons you require cac or wr

CC takes care of completly different component things

**Comment by CptMoore** [comment]
CC and ME dont seem related to the issues described, LadyAlekto knows what she is talking about here.

CC allows to specify custom attributes to already existing components, but those custom attributes have to still be read and processed, which CC doesn't actually do itself.
