### ISSUE TITLE
Hardpoint Fix: Can't add Machine Guns to Shadowhawk's left torso

### ISSUE THREAD

**Issue by clintonmead** [BattletechModders/MechEngineer#152]
With the following in the `settings.json`:

```
    "HardpointFix" : {
        "Enabled" : true,
        "AutoFixChassisDefWeaponHardpointCounts" : true,
        "EnforceHardpointLimits" : true,
        "AllowDefaultLoadoutWeapons" : false
    }
```

I can't add machine guns to the a Shadowhawk's left torso in the skirmish mech lab, despite the mounts appearing in the hardpointdatadef file for the Shadowhawk. 

Is this a bug or am I misunderstanding how this mod works?

**Comment by CptMoore** [comment]
Either I dont understand my feature anymore or you are right, thats a bug... I'm investigating

**Comment by CptMoore** [comment]
should be fixed in the latest release, there was some issue with case sensitivity which lead to only searching for "machinegun" prefabs instead of also "mg" prefabs
