### ISSUE TITLE
Hardpoint fix: Unable to add additional small laser to Hunchback right torso after adding two machine guns

### ISSUE THREAD

**Issue by clintonmead** [BattletechModders/MechEngineer#153]
I can't add the following weapons to the Hunchback's right torso in this order:

1. Machine gun
2. Machine gun
3. Small laser

Note I can do this:

1. Machine gun
2. Small laser
3. Machine gun

And I can do this:

1. Machine gun
2. Machine gun
3. Medium laser

I thought all lasers came under the same category so I'm not sure why a small laser is rejected and a medium laser isn't, and the order of adding them making a difference does seem buggy.

Note also there's a few other issues, like I can't add the weapons in the following order:

1. SRM6
2. Machine gun
3. Small laser

But I can do this:

1. SRM6
2. Small laser
3. Machine gun

My `settings.json` is below.

By the way this mod makes the mechs look great, and having the visual hardpoints as the only restriction breaths a bit of extra life into smaller mechs as it gives them a lot more flexibility.

```
{
    "AccuracyEffects" : {
        "Enabled" : false,
    },
    "ArmActuator" : {
        "Enabled" : false,
    },
    "ArmorStructureChanges" : {
        "Enabled" : false,
    },
    "ArmorStructureRatio" : {
        "Enabled" : false,
    },
    "AutoFixer" : {
        "Enabled" : false,
    },
    "BattleTechLoadFix" : {
        "Enabled" : true,
    },
    "ComponentExplosions" : {
        "Enabled" : false,
    },
    "CompressFloatieMessages" : {
        "Enabled" : true,
    },
    "CriticalEffects" : {
        "Enabled" : false,
    },
    "DebugCycleCombatSounds" : {
        "Enabled" : false,
    },
    "DebugSaveMechToFile" : {
        "Enabled" : false,
    },
    "DynamicSlots" : {
        "Enabled" : false,
    },
    "Engine" : {
        "Enabled" : false,
    },
    "Globals" : {
        "Enabled" : false,
    },
    "HardpointFix" : {
        "Enabled" : true,
        "AutoFixChassisDefWeaponHardpointCounts" : true,
        "EnforceHardpointLimits" : true,
        "AllowDefaultLoadoutWeapons" : false,
        "WeaponPrefabMappings" : [
            {
                "PrefabIdentifier" : "AC2",
                "HardpointCandidates" : [
                    "ac2",
                    "ac",
                    "lbx"
                ]
            },
            {
                "PrefabIdentifier" : "AC5",
                "HardpointCandidates" : [
                    "ac5",
                    "uac5",
                    "ac",
                    "lbx"
                ]
            },
            {
                "PrefabIdentifier" : "AC10",
                "HardpointCandidates" : [
                    "ac10",
                    "lbx10",
                    "ac",
                    "lbx"
                ]
            },
            {
                "PrefabIdentifier" : "AC20",
                "HardpointCandidates" : [
                    "ac20",
                    "ac",
                    "lbx"
                ]
            },
            {
                "PrefabIdentifier" : "artillery",
                "HardpointCandidates" : [
                    "artillery",
                    "ac20",
                    "ac",
                    "lbx"
                ]
            },
            {
                "PrefabIdentifier" : "lrm5",
                "HardpointCandidates" : [
                    "lrm5"
                ]
            },
            {
                "PrefabIdentifier" : "lrm10",
                "HardpointCandidates" : [
                    "lrm10"
                ]
            },
            {
                "PrefabIdentifier" : "lrm15",
                "HardpointCandidates" : [
                    "lrm15"
                ]
            },
            {
                "PrefabIdentifier" : "lrm20",
                "HardpointCandidates" : [
                    "lrm20",
                    "srm20"
                ]
            },
            {
                "PrefabIdentifier" : "MachineGun",
                "HardpointCandidates" : [
                    "machinegun",
                    "mg"
                ]
            },
            {
                "PrefabIdentifier" : "srm2",
                "HardpointCandidates" : [
                    "srm2"
                ]
            },
            {
                "PrefabIdentifier" : "srm4",
                "HardpointCandidates" : [
                    "srm4"
                ]
            },
            {
                "PrefabIdentifier" : "srm6",
                "HardpointCandidates" : [
                    "srm6"
                ]
            }
        ]
    },
    "InvalidInventory" : {
        "Enabled" : false,
    },
    "LocationalEffects" : {
        "Enabled" : false,
    },
    "MechLabSlots" : {
        "Enabled" : false,
    },
    "MoveMultiplierStat" : {
        "Enabled" : false,
    },
    "NewSaveFolder" : {
        "Enabled" : false,
    },
    "OverrideDescriptions" : {
        "Enabled" : false,
    },
    "OverrideGhostVFX" : {
        "Enabled" : false,
    },
    "OverrideTonnage" : {
        "Enabled" : false,
    },
    "ShutdownInjuryProtection" : {
        "Enabled" : false,
    },
    "TurretLimitedAmmo" : {
        "Enabled" : false,
    },
    "TurretMechComponents" : {
        "Enabled" : false,
    }
}
```

**Comment by CptMoore** [comment]
The install order should definitely not matter, must be another bug.

Small laser and medium lasers are in different weapon categories but in the same hardpoint category.

> having the visual hardpoints
I totally agree! Why I made this mod in the first place. Immersions is extremely important for me, that includes lore immersion too (so I can talk with TT guys about the same game).
In lore LRM20 launchers can fit in LRM5/10 slots, the atlas LRM launcher is an example. (So shame on you for not having that enabled in the settings :D )

**Comment by CptMoore** [comment]
Ah the hunchback, I remember, its one of the mechs that uses a different hardpoint convention from everything. Probably the first prototype of the game had the hunchback in it, it also counts the hardpoints very strange.

**Comment by clintonmead** [comment]
Ah, good point about the Atlas. That's annoying because I just checked the model does not show the LRM20. 

If you want me to have a poke at the code I'm happy to if you can point me in the direction of the code that does the hardpoint checking and assignment (which I presume are the same).

**Comment by CptMoore** [comment]
I'm fixing the mech hardpoint definitions for the hunchback, and also found an issue with the cyclops. There are probably more but they must be well hidden.

For the LRM, it just doesnt have the LRM20 as a visual, in lore the launcher sends out the missles of an LRM20 in waves for the atlas. See [SARNA/Atlas](http://www.sarna.net/wiki/Atlas_(BattleMech))
> Unable to fit a full twenty-tube system on the 'Mech, the FarFire instead launches the missiles in waves of five over the course of ten seconds and carries two tons of reloads for twelve such salvos.

**Comment by CptMoore** [comment]
I've made a new release that contains fixes I mentioned before.

**Comment by clintonmead** [comment]
Much improved, but now I've got the issue with this add order:

1. Machine Gun
2. Machine Gun
3. Machine Gun
4. Medium Laser

**Comment by CptMoore** [comment]
ok that makes no sense to me at all.. small laser works but medium doesnt for you 4.
small laser = medium laser as bot are "laser", so what goes?

investigating

**Comment by clintonmead** [comment]
On the Griffin, this works fine:

1. LRM5
2. Large Laser

But this fails:

1. LRM10
2. Large Laser

It seems as though the weapons are being sorted by mass and then being assigned to hardpoints top to bottom, which may mean in some cases some valid hardpoint mappings are not found, in particular when heavier weapons need to be assigned to latter hardpoints.

**Comment by CptMoore** [comment]
ok, this is what happens... so medium laser is more bulky than a small laser.. so the medium gets sorted first... 1. slot allows to take a medium so it gets associated there. 2. gets mg 3. get mg 4.... well no space for mg

**Comment by CptMoore** [comment]
> It seems as though the weapons are being sorted by mass and then being assigned to hardpoints top to bottom, which may mean in some cases some valid hardpoint mappings are not found, in particular when heavier weapons need to be assigned to latter hardpoints.

Yea exactly, that I how I remember it now, you can look into https://github.com/BattletechModders/MechEngineer/blob/master/source/Features/HardpointFix/utils/WeaponComponentPrefabCalculator.cs

**Comment by CptMoore** [comment]
I now remember why I made it that way.. immersion. You want the biggest gun to be the most prominent, and guess what.. the 1. slot is usually modeled to be the big prominent gun. I had issues on some mechs which looked ugly when using different algorithms, that's why I commented code that allowed for better selection.

Since immersion > than gameplay I opted to use the simpler algorithm.

Now there is one exception I could make though... lasers look the same no matter if they are small or large, so basically they could be reordered much without any effect.

Maybe I can make a list of things that count as BIG and use them as priority, and use the other algorithm for SMALL stuff (including lasers).

What do you think?

**Comment by clintonmead** [comment]
I'm not sure that works. In the case of the Griffin, putting the lasers in last (as one with they were small) causes the issue. I guess if one put them in first but in reverse hardpoint order that might work.

But I think this approach is better:

1. For each weapon (smallest to largest) put it in the first hardpoint it fits and isn't already occupied, trying the last (i.e. lowest) hardpoint first.

As generally the lower hardpoints are either subsets of or disjoint from the upper hardpoints, this approach should give a hardpoint mapping if one exists.

This will also order the larger weapons towards the higher hardpoints.

But we still have one problem: there may be upper hardpoints unfilled which could be.

So then:

2. For each currently occupied hardpoint (first to last), move the weapon to the highest unoccupied hardpoint it can fit into. 

This second stage will attempt to push up the hardpoints, but it will never turn a valid mapping into an invalid one, so at least we won't get unexpected issues with not being able to fit weapons into hardpoints.

**Comment by CptMoore** [comment]
1. is what was already implemented before I switched to the current algorithm
2. that is something I didnt think was feasible at the time I did the current algorithm, because moving stuff up would sometimes interfere with stuff already placed since they didnt fit below, so hard to know everything. (e.g. if we have weapon A in slot 3 and weapon B in slot 2, but weapon A is bigger than B, if we would move everything up (if possible), weapon A is still not on top but it should be)

I guess I first have to find a nice representation of slot possibilities and then just find a dynamic programming solution that prioritizes higher slots. Probably something that works by inserting stuff and trying to recursively move stuff around after each insert.

If you good in that stuff, you can try to do that, otherwise I'll refresh my knowledge and try tomorrow or next WE.

**Comment by clintonmead** [comment]
Cheers thanks for working together on this. I'll have a poke at it on the weekend, if you're busy with other stuff don't worry about it too much, from the code you pointed me too is pretty clear so I should be able to hack at it. 

It's potentially an O(n!) size problem where n are the number of hardpoints but I'll try to write something that works far better in the majority of cases (i.e. either quickly succeeds or fails quickly).

**Comment by CptMoore** [comment]
I refactored some stuff, you can try it out with [MechEngineer.zip](https://github.com/BattletechModders/MechEngineer/files/3292793/MechEngineer.zip)

The related code I have already pushed in the repo.

**Comment by CptMoore** [comment]
well the new selection algorithm is in the release, so I'll close this
