### ISSUE TITLE
Adding Double Heats Cooling adds extra tonnage if core heat sinks under 10

### ISSUE THREAD

**Issue by Admiralbrad** [BattletechModders/MechEngineer#155]
Hi Captain,

I was playing this morning and finally picked up some DHS to add to my mech.  When I added Cooling (DHS) to my Vindicator and Blackjack (7 Core HS) my weight increased by 3 tons.  I tried the Phoenix Hawk (10 Core HS) but no change.  When I tried my Centurion (8 Core HS) it increased by 2 tons.

If you remove the engine, add Cooling (DHS) and then add the engine back it does the same as above.

However, if you strip the mech of all equipment and add then rebuild it (same loadout) with the Cooling (DHS) everything is fine (except the 60 extra days of shop time).
![20190616094453_1](https://user-images.githubusercontent.com/51839552/59566385-e8c1a680-901c-11e9-95ce-51bcfeeb67ae.jpg)

**Comment by CptMoore** [comment]
DHS is incompatible with SHS, and if you install DHS in the mech, all "free" SHS tonnage suddenly isn't counted as free anymore and the mech becomes invalid. You can set AllowMixingHeatSinkTypes to true but then it still doesn't count the SHS as free and just as additional.

By default the engine contains rating/25 heat sinks to a max of 10. If it has less than 10 you can mount free heat sinks (of the same type) on the mech.. that just use up space but not tonnage.

**Comment by Admiralbrad** [comment]
Okay.  Tested that and it worked as expected.  I guess I never had the opportunity to add DHS to a lighter mech before.
