### ISSUE TITLE
Capture the Argo Centurion comes with a 345 rated Engine.

### ISSUE THREAD

**Issue by Admiralbrad** [BattletechModders/MechEngineer#156]
Hi Captain,  Thanks for responding on that DHS thing so quickly.

I finished the Capture the Argo mission the other day and the stripped down Centurion came with a 345 engine instead of a 200.  I suspect this is because most of the weapons are stripped off of it, thus changing the free/weapon space which must be used by your auto-math to get engine size.

**Comment by CptMoore** [comment]
do you know any other mechs that are stripped down? I can put them under "ignored" so they don't get oversized engine cores

**Comment by Admiralbrad** [comment]
Not that I know of.
