### ISSUE TITLE
Turrets are not using Upgrades/Heatsinks

### ISSUE THREAD

**Issue by LadyAlekto** [BattletechModders/MechEngineer#157]
Basically Engines and Upgrade type items make turrets break, either not loading or cause issues

Ontop Upgrades do not apply their Status effects as they should

I would very much appreciate if they could be taught to use every item like vehicles to

(no need to apply engine speeds or the like, just that it accepts these to exist on the turret)

**Comment by CptMoore** [comment]
- based on static code review, turrets should have their status effects applied, nothing wrong there (anyone can confirm this?)
- even critical effects should work.. if there is a mod installed that allowed for critical hits on turrets (AIM did support it at one point in time)
- heat sinking is not implemented for turret (as far as I can tell)
- engines are not supported on turrets (engine code is hardcoded to MechDef; no TurretDef or even VehicleDef)

TODOs:
- generalize engines and allow turrets and vehicles
- add heat sinking to turrets
- find a way to make AIM work again with turrets or so
