### ISSUE TITLE
autofixer forces max jump jump jets

### ISSUE THREAD

**Issue by konstantinavalentina** [BattletechModders/MechEngineer#158]
Hello,
I'm playing Bettletech 1.62 with XLRP mod that comes with Mech Engineer.  
As is, everything works.  
I, however, want to edit max jump jets on some of the mechs.  In theory, I should be able to do this by changing the Max Jump Jets value in the mech chassis json file.  
Unfortunately, Mech Engineer will not allow these changes to take effect, and, looking at the log.txt file in the Mech Engineer folder, it appears the autofixer enforces it's own predefined will.  
I thought the Mech Engineer settings.default true/false values for Max Jumpjets could be changed, but, the values do nothing and revert to "true" enforcement on game launch.  

I do not know anything about DLL files, but, I suspect the Mech Engineer DLL file has those autofixer instructions?   I've attempted to open the DLL file using different resource editor programs, but, can only see Mech Engineer Version Information.  I don't know what I'm doing when ti comes to a DLL file, and I feel like I've exhausted my options, so, I'm commenting here.  

How can I disable the Autofixer or Mech Engineer from forcing/enforcing Mech Engineer Jump Jet rules?  
This mod is otherwise wonderful work.  I'm just a little crabby about not being able to customize the values that the Autofixer is enforcing ... or, I haven't found where/how to change that?
My ignorance for this one thing is frustrating.
Thank you for your work and any assistance, guidance, or how-to information you might offer.

**Comment by CptMoore** [comment]
the values have to be set in Settings.json

**Comment by konstantinavalentina** [comment]
Yes, but, if you change the values in the settings.json, change the Max Jump Jets from 8 to any number, or change the value of "true" next to the Max Jump Jets number to "false", or even change the value of "true" next to "Enabled" under Autofixer to "false", and launch the game, the settings.json changes back on game launch.  
It's more like the settings.json file is a description of settings set somewhere else, and nothing done to that file makes a difference because it rewrites itself on game launch.  
... at least that's been my experience so far.  
Thinking about it now, about the only thing I think I haven't tried is changing the read/write permissions on that file to read-only, but, I don't think the settings.json file is instructions, more so than it is a description of instructions set somewhere else since the log.txt file describes actions by the Autofixer not all of which are described by settings.json.
  
[log.txt](https://github.com/BattletechModders/MechEngineer/files/3389815/log.txt)

For instance, a mod mech I'm testing this one, the GP Mad Cat Mk II has 7 jump jets listed as max jumpjets in its chassis file; chassisdef_madcatmkii_4,

The settings.json file in Mech Engineer has Max Jumpjets listed as 8

        "ChassisDefMaxJumpjets" : true,
        "ChassisDefMaxJumpjetsCount" : 8,
        "ChassisDefMaxJumpjetsRating" : 400,

... yet, the log.txt file shows the following for that mod mech I'm testing with.   

00:47.387 [LOG  ] MechEngineer Auto fixing chassisDef=chassisdef_madcatmkii_4
00:47.387 [DEBUG] MechEngineer set InitialTonnage=9
00:47.387 [DEBUG] MechEngineer set MaxJumpjets=4

Nowhere have i found a setting that describes forcing that Mod Mech to have 4 jump jets, yet, it happens.

**Comment by CptMoore** [comment]
no you are changing settings.defaults.json .. that reset every time you start the game

you have to copy the relevant sections from the defaults into settings.json and then it should use those settings, you can verify they are used with settings.last.json

I'll probably rename settings.json to settings.override.json or so.. to make it clearer

**Comment by vengefire** [comment]
I'm not sure the proposed name change is necessary, given that it will break the current pattern many other mods use? Once you understand the settings.defaults.json paradigm, you're golden, and people will still get confused with settings.override.json anyhow, I think.

**Comment by konstantinavalentina** [comment]
Okay, Thank you for the enlightenment and help.  

I put 

        "ChassisDefMaxJumpjets" : false,

into the settings.json and that seems to work.
  
It might be more elegant if I were to use the chassisdef (or what?) for a specific mech in the skipmechdefs area, but, I tried that first, and it didn't result in any noticeable change in behavior of the game, 
I suspect I'm doing it wrong.  
I do a lot of things wrong, but, that's how I learn.  :)
Do you have any recommendation?

I'm still curious where the jump jets getting set to 4 globally, automatically, for all assault mechs comes from since the default max jump jets shown in settings default shows 8, and all the vanilla assault mechs are set to 3 before mods?

As to renaming; I'm with the previous poster.  Renaming will just be a pain to everyone already familiar with how it is set up.   If you just expand on the comments inside each file that gives descriptions for idiots like me; "this is the file you put changes into", "this file does not change and only shows defaults.  make changes to the settings.json file, not this one",  "this file only shows changes that have been made and are currently in effect.  If you want to make changes use the settins.json file".   :)

**Comment by vengefire** [comment]
You're not an idiot mate, experimentation is the basis of scientific method. Breaking something gives you the opportunity to fix it, and by fixing it you uncover how things work. Keep on breaking things, asking questions, and getting the broken things to work, and you'll be an expert in short order 👍 

Incidentally, do you have any coding skills? If you do, then you can clone or fork the source, and poke around the code. Being on github is a good start. Even if you don't currently have coding experience, it's pretty cool to figure out the answer to questions you have by reading the code and figuring it out. You might like it, and discover a new hobby 😃 

Have a good one!

**Comment by konstantinavalentina** [comment]
I have no coding experience.  I do, however, like puzzles, and i really only ever like games, not ones with puzzles, but, games that have modding community, because I get ideas i want to do, so, I try to customize mods, figure out how they work, and ask questions like I have here.  
... so, I'm a secondary, modder?   I never make original content, just personalize the awesome work that others have made?   ... not that there is anything wrong with any work done by anyone else.  I just see what changes they make and wonder what changes I can make and how I can make them.

... like with the jump jets here.  
I'm still curious where the 4 jump jets number comes from for the assault mechs in the default mod?
The maxjumpjets in settings.default is set to 8?   
The vanilla setting for all assault mechs is 3 jump jets?
When Mech Engineer is installed jump jet number on Assault Mechs goes up from 3 to 4.  
I can't find where or how that happens.     
I suspect it's a plus or minus variable calculation applied to mech weight classes, but, i can't confirm or debunk that assumption.   
I'm still curious about how that happens, or I would have clicked on the "closed" button for this topic after getting the bulk of my question answered and solved regarding how to add more than was previously allowed.  :)

**Comment by vengefire** [comment]
Ah, a problem solver by nature. You should look into coding, it gives you
innumerable problems to solve. Go pro and you get paid for it at the same
time, although it can be tedious at times...

I'll have a quick look and see if I can give you your answer so you can
close the issue. Gives me a problem to find an answer to 😁.

**Comment by vengefire** [comment]
I've got some things I need to attend to, but a quick look at the code suggests that the maximum number of jump jets are determined by your engine rating / mech weight to give you a movement points value, and then to either floor or ceiling that value to an int based on a setting called JJRoundUp in the Engine settings in the settings.json file. This value defaults to false.

e.g.
Atlas Weight = 100 tons
Engine Rating = 340
Movement Points = 3.4 (340 / 100)
Jump Jets = 3 if JJRoundUp = false, 4 if JJRoundUp = true.

If you had a lighter Assault, like an Awesome:
340 / 80 = 4.25, rounded down by default = 4.

**Comment by konstantinavalentina** [comment]
okay!

Thank you so much for the help.
That answers the question and gives me something to maybe look at and think about.   :)
