### ISSUE TITLE
Mech Lab General Widget - Hardcoded Slot Count Query

### ISSUE THREAD

**Issue by vengefire** [BattletechModders/MechEngineer#159]
Hey CptMoore,

I'm tinkering about with adding mech quirks via custom ME categories and the Mech General Widget, and I came across the following while reviewing the code...

In the MechLabPanel_InitWidgets_Patch.PostFix function, the call to MechLabLocationWidget_SetData_Patch.ModifySlotCount hardcodes the maximum slot count to 3, instead of using MechLabSlotsFeature.settings.MechLabGeneralSlots.

Is there a specific reason the value is hard coded to 3? The location widget decrements the CenterTorso slot count by the general slot count setting, it looks like everything should be handled appropriately.

Just looking for your input before I waste too much time on this. If there are more considerations to the idea, then I'll just go the round-about way of doing so.

**Comment by CptMoore** [comment]
its just an oversight
