### ISSUE TITLE
question:how do you  use only  the hardpoint fix mod and does it work with battletech 3025 CE?

### ISSUE THREAD

**Issue by reaverbad** [BattletechModders/MechEngineer#160]
Hello

I have seen that you already have answer to a similar question in the past so I excuse myself for asking approximately the same question but I didn't really understood the answer:do i have to go to the mechengineer setting file and delete all the feature or do i need to go the the feature list and delete all the feature in this file ?
I've tried both and it seems that it make the mod unload-able by the game so i was wondering if i made a mistake?
Last question:is this mod ( in particular hardpoint fix mod )compatible with Battletech 3025  commander edition? If not ,do not worry i will just do without this mod so don't  waste time answering the 2 question above.
Sorry for the broken English and have a nice day.

**Comment by CptMoore** [comment]
the hardpointfix should be compatible

you have to go through all features and disable them save for the hardpointfix mod
basically you could take the default settings copy them to the normal one... delete all entries for all features except for the "enabled" parts and it should work.

**Comment by reaverbad** [comment]
Thanks you for the answer .
