### ISSUE TITLE
Eliminating the Failure When Prefab Selection Fails

### ISSUE THREAD

**Issue by LtShade** [BattletechModders/MechEngineer#161]
When the game cannot find an appropriate fallback prefab, it fails to load the Mech which in MechBay will cause the Mech/MechBay preview to not appear and when loading into mission will cause an ever-spinning wheel. This drastically limits the modelers' options for weapons, especially for Omni mechs where we need at least three prefabs per Omni hardpoint to ensure that the model will load. Additionally, if a typo in the prefab name causes a no-match situation during our model testing, we can simply see that the model did not load rather than having to force close BTG and wait on a full game restart to attempt again after a correction.

I believe vanilla Mechs are immune to this issue but I have not yet confirmed.

An example of what would cause an error:
hardpointdatadef.json contains:
`            "location" : "centertorso",
            "weapons" : [
			[
				"chrprfweap_templar_centertorso_laser_eh1"
			],
			[
				"chrprfweap_templar_centertorso_laser_eh2"
			]
            ],`

mod.json contains:
`			{ "Type": "Prefab","Path": "assets/character/mechs/prefabs/weapons/templar/chrprfweap_templar_centertorso_laser_eh1.prefab", "AssetBundleName": "chrprfmech_templarbase-001" },
			{ "Type": "Prefab","Path": "assets/character/mechs/prefabs/weapons/templar/chrprfweap_templar_centertorso_laser_eh2.prefab", "AssetBundleName": "chrprfmech_templarbase-001" },`

A mechdef for the Templar has an SRM6 in the Center Torso.
This will result in MechEngineer looking for an SRM6 and then any missile hardpoint and it will fail to find any for this location. 

From my perspective, the ideal solution is to find a way to instruct BTG to ignore loading the prefab if MechEngineer cannot find one suitable. Failing that, make BTG call a universal "blank" prefab when this situation occur.

If you have any questions or want more information, I will be happy to help out the best I can. Just @ me on Discord
-LtShade

**Comment by CptMoore** [comment]
```hardpointDataDef.HardpointData[0].weapons[0][0]```

That is what vanilla code is returning, and what ME should also return. Maybe there were some issues with falling back to vanilla code, so I disabled the fallback to vanilla code and just hardcoded the above statement.
