### ISSUE TITLE
Custom ammo without XLRP

### ISSUE THREAD

**Issue by st3fan21** [BattletechModders/MechEngineer#163]
How can i get custom ammo in stores/salvage now that XLRP is no longer updated for 1.7?

 This is from the author of XLRP:

XLRP is no longer being maintained. If someone else wants to continue development of the mod as a fork, I'm willing to endorse their work to keep the project alive.

The mod is probably not going to work with 1.7 for different reasons, the most likely being the various third-party .dll files (like Custom Ammo Categories / AIM for example). Those would have to be replaced with new versions made for the latest ModTek. Other related files will then require updates as well. Currently I do not have any plans to update the mod, so the mod is only going to work as is on 1.6.2.

 

Anyway, maybe I'll post more about this on the Paradox BATTLETECH forum soon - that is, if I am allowed to post in my own mod thread again.

**Comment by CptMoore** [comment]
you probably should start with https://www.nexusmods.com/battletech/mods/381 then, thats where custom ammo is from...

damn, I really could use XLRP .. really liked it

**Comment by vengefire** [comment]
I'm trying to get permission from exterminator 2K to continue the project.
Once I have obtained (or not) said permission, I will post a notice on
Reddit regarding the plans for XLRP.
It'll definitely be coming back at some point in the future, date
contingent on the release of Heavy Metal.

**Comment by st3fan21** [comment]
I loved XLRP too... 
Vengefire, this guy is the author/owner of XLRP, and he wants someone to continue his project:

XTRMNTR2K

https://www.nexusmods.com/users/186910

This was his private message to me 2-3 days ago:
"XLRP is no longer being maintained. If someone else wants to continue development of the mod as a fork, I'm willing to endorse their work to keep the project alive.

The mod is probably not going to work with 1.7 for different reasons, the most likely being the various third-party .dll files (like Custom Ammo Categories / AIM for example). Those would have to be replaced with new versions made for the latest ModTek. Other related files will then require updates as well. Currently I do not have any plans to update the mod, so the mod is only going to work as is on 1.6.2.

Anyway, maybe I'll post more about this on the Paradox BATTLETECH forum soon - that is, if I am allowed to post in my own mod thread again."

I saw you are also friends on NEXUSMODS, so for sure he will give you his permission and you can continue.

I really hope until u update (probably after HEAVY METAL) i can find incendiary rockets for srm and lrm in stores or salvage.

**Comment by CptMoore** [comment]
lets hope XLRP gets updated or another mod picks up ME for a lightweight CBT experience
