### ISSUE TITLE
HM Mortar issues

### ISSUE THREAD

**Issue by CptMoore** [BattletechModders/MechEngineer#164]
Kmission says user reported issue with mortars and hardpointfix

either there are some workaround by HBS that have to be known or the settings json is just out of date or some enum values are missing?

**Comment by CptMoore** [comment]
some people reported a similar issue with ME, so not sure if ME is the reason it doesn't work

**Comment by YaoOcelotl** [comment]
I have an issue in HM, when I use artillery (mortar or thumper cannon) the fire animation does not start soft locking the game. 

At the top of the stack is _MechMortarSequence [CameraSequence][C]_

CombatLog:

> CombatLog.AbilitiesAndEffects [LOG] Bull Shark activates ability THUMPER CANNON on position (-100.3, 284.7, 699.6)
> CombatLog.InvocationHandler [LOG] Invoking INVOCATION: ID = P1TDG.33, type = MechMortarInvocation, seed = 94065, netRouted = True, wasNetRouted = False @ Tue Dec 10 2019 22:39:16
> CombatLog.Heat [LOG] Mech Bull Shark (d7b3b2a0-a5ea-449b-8f20-e75ec9593a8b.0) gains 60 heat. Reason: Mortar Launch Heat

**Comment by CptMoore** [comment]
yea was analyzing the issue yesterday with someone, have a workaround but I want to try to fix it for good
in the meantime just disable the HardpointFix feature

**Comment by CptMoore** [comment]
the new release ME1.8.1 has this fixed, when searching for weapons hardpointson the mech we fall back to vanilla code. that unfortunately will map SRMs weapons to e.g. AC10 weapon hardpoints visually.

there are lots of errors being logged right now, but those are harmless (logging is fixed in source and for next release)
