### ISSUE TITLE
Hy Cpt Moore, Custom Salvage is no longer working, 

### ISSUE THREAD

**Issue by st3fan21** [BattletechModders/MechEngineer#165]
Custom Salvage is no longer working, any other mods that let you create different variants from a few different parts?

**Comment by CptMoore** [comment]
dont know if thats related to MechEngineer, you can try disabling the TagManager in settings.json

**Comment by st3fan21** [comment]
I ll try. Actually the game starts with custom salvage. And the save game loads. The problem is in the Mechbay the buttons for Ready mech and scrap Mech no longer work you just press them and they do nothing

**Comment by st3fan21** [comment]
Tryed to disable TagManager in settings.json, did not work. So everything works, except the ready mech button and the scrap mech button.

**Comment by CptMoore** [comment]
@Denadan any ideas?

**Comment by st3fan21** [comment]
I tryed contacting Denadan, but i received an updated Custom Salvage mod from sqparadox. Works great even in 1.8.1.
I have a new issue. When i install Custom Components and Mech Engineer 1.8.1 the game no longer recognizes my mod saves, only my old vanilla saves.

**Comment by CptMoore** [comment]
oh, yea I removed the save game folder redirection feature (not 100% compatible with modloader), your save games are in BATTLETECH/Mods/Saves and need to be moved to the original save game location %LocalAppData%\..\LocalLow\Harebrained Schemes\BATTLETECH

**Comment by CptMoore** [comment]
if the saves are not recognized after moving manually, please tell me, I can re-add the save redirection feature but that will take some effort and time

**Comment by st3fan21** [comment]
Already tryed. Does not seem to work. I Also disabled cloud saves first. Then tryed with cloud saves enabled. Dont know whats going on. I would prefer to have the saves in just the steam place (C:\Games\Steam\userdata\{your user id}\637090\remote\C0). But it s not working

**Comment by st3fan21** [comment]
I ll try again tonight

**Comment by st3fan21** [comment]
I tryed again, with and without cloudsaves enabled, each time copying the saves from the mods folder to the steam userdata ... folder. (once i tryed deleting my vanilla saves from the userdata folder). Nothing works. 

But, for now, Custom components and mech engineer 1.8.0 work with version 1.8.1, so i can wait until you fix this.

**Comment by CptMoore** [comment]
hey there, no I can managed, I will move the save games to the mod folders though

**Comment by st3fan21** [comment]
Ok. I forgot to ask but the folder structure in the mods\saves\ is differentthat in the userdata\.... \ saves\
There are 2 extra folders in the mods\saves\:
cloud 
local
+one file: CachedSettings.pref

In the cloud folder u find the C0 and in the local u find an S0 folder with two files settings_local.sav and marketing.sav

**Comment by CptMoore** [comment]
ok, bad news, its just too incompatible to make it work reliably... in the end the saves are supposed to be in "C0\SGS1".
can you retry the move?
move/copy the .sav files that have uuids (e.g. 550e8400-e29b-11d4-a716-446655440000.sav) as names from the Mods/Saves directory to that <steam dir>\userdata\<you user id>\637090\remote\C0\SGS1 directory

so e.g...

Before:
Mods/Saves/550e8400-e29b-11d4-a716-446655440000.sav

After:
<steam dir>\userdata\<you user id>\637090\remote\C0\SGS1\550e8400-e29b-11d4-a716-446655440000.sav

**Comment by st3fan21** [comment]
Ok, i m playing now. So i ll save and follow ur instructions.

**Comment by st3fan21** [comment]
Just checked. This is already how i tryed. This is the folder structure:
C:\GAMES\Steam\steamapps\common\BATTLETECH\Mods\Saves\cloud\C0\SGS1
and i copyed them to:
C:\GAMES\Steam\userdata\35349689\637090\remote\C0\SGS1

**Comment by st3fan21** [comment]
I think this may be because i used to have cloud saves enabled?

**Comment by st3fan21** [comment]
Tryed again, nothing seems to work with mech engineer 1.8.1, but when i use mech engineer 1.8.0 everything works. Battletech's version cant be downgraded to 1.8.0

**Comment by CptMoore** [comment]
damn, tbh I dont even know how the old mechengineer works due to the issues I'm facing

I'll try to find out if there is some kind of index

**Comment by st3fan21** [comment]
Well mech engineer 1.8.0 works without any issues for me right now. 
I can send you anything you want to help you investigate. 
Do you want me to zip the saves and maybe something else you need and send them through wetransfer?

**Comment by st3fan21** [comment]
I even tryed putting the saves in every possible configuration in the user and the mods folders at the same time.
![Untitled](https://user-images.githubusercontent.com/49989588/70751608-7d416300-1d39-11ea-8131-adc75d14125a.png)

**Comment by CptMoore** [comment]
i dont have the same mods so probably the saves wont work for me either way

can you try creating new saves in the new location... copying them out... deleting them from within the game.. and then putting them back
thats what i tried and it works, the "deleted" save reappeared

maybe there is some checksum or something saved in the normal settings files, but if i delete those it still works.

![howitworksforme](https://user-images.githubusercontent.com/39010654/70752749-87606300-1d33-11ea-813e-a96d274f2e57.png)

all those saves were deleted by me ingame and then added back using filecopy

**Comment by CptMoore** [comment]
also having cloud disabled or enables doesnt matter, it always seems to save in C0

**Comment by st3fan21** [comment]
ok

**Comment by st3fan21** [comment]
Followed your instructions. It doesnt work for me. 
I created 3 saves. 
Copyed them out
Used the ingame menus to delete all of them
The game  deleted C0 and SGS1 folder, i recreated these.
Copyed saves to C:\GAMES\Steam\userdata\35349689\637090\remote\C0\SGS1
The game doesn t see them

**Comment by st3fan21** [comment]
Well for now i ll keep using ME 1.8.0
I am using MODTEK the latest version btw, it s compatible with the game mod loader. Should i try with the game mod loader also?

**Comment by CptMoore** [comment]
oh, thats why the save game feature works for you, you are using modtek and not the modloader

well doesnt explain why your save game copying doesnt work, really confused

**Comment by st3fan21** [comment]
Just tryed using the modloader. Nothing changed. Reinstalled the game. Did not solve anything.

**Comment by st3fan21** [comment]
Also tryed removing most mods except mechengineer and cutom components. :( Did not work

**Comment by st3fan21** [comment]
Tryed it again before i went to work today with MODLOADER and it worked. Maybe i did something wrong yesterday or idk. Now i see both my vanilla saves (very old) and my modded saves. 

The only thing is MODLOADER does not properly load the SKIPINTRO mod. When i was using MODTEK, SKIPINTRO also skipped past the 3 short developer videos (harebrained,paradox, unity). With MODLOADER it only skips the main intro video and doesnt skip the 3 short developer videos.

But, this is such a small thing that i dont really care.

The main thing is Mech engineer 1.8.1 seems to work perfectly.
 ( I did see an enemy jagermech jm6-A that looked like the jagermech jm6-S, but this is again not important, and could be caused by other mods)

**Comment by CptMoore** [comment]
Hmm I did see some save fixing code, maybe that has to run first before showing save games or so and by chance now it worked for you.

Anyway, HBS actually added their own skipintro setting somewhere to fix the issue that mods are loaded after the intro with the modloader. Don't know how to set it up or if it even works.

**Comment by CptMoore** [comment]
BTA was using the save game feature too, so there is now a modtek only mod, where the save game redirection can still work properly
https://github.com/BattletechModders/NewSaveFolder
