### ISSUE TITLE
Version 2.0.0 kind of breaks Mechlab

### ISSUE THREAD

**Issue by st3fan21** [BattletechModders/MechEngineer#167]
Version 2.0.0 messes up the mechlab interface, at least on 4k resolution.

I lltry to post a photo. The main problem is the general section overlaps the tonnage, the center torso overlaps the head and so on, some parts are inaccesible

**Comment by CptMoore** [comment]
you mean earlier versions didnt have the problem or just that the current version has the problem?

in any case only tested this with 1440p, so 4k screenshots would be nice

**Comment by CptMoore** [comment]
code used for zooming the mechlab:
https://github.com/BattletechModders/MechEngineer/blob/master/source/Features/MechLabSlots/MechLabAutoZoom.cs

**Comment by st3fan21** [comment]
Up until 10 days ago i had an 3440x1440 monitor. Now i have a 4k monitor. 

I tested a little. When you first load the game the mechlab is fine. After you finish a mission and enter the mechlab it s messed up

**Comment by st3fan21** [comment]
Here are screenshots of the problem

**Comment by st3fan21** [comment]
![1](https://user-images.githubusercontent.com/49989588/71033513-139dcc00-2120-11ea-9261-a2a62038e018.png)

**Comment by st3fan21** [comment]
![2](https://user-images.githubusercontent.com/49989588/71033522-1ac4da00-2120-11ea-8e9d-19e0335a919c.png)

**Comment by st3fan21** [comment]
![3](https://user-images.githubusercontent.com/49989588/71033612-4f389600-2120-11ea-8532-9ac525cbe63a.png)
Same as previous

**Comment by CptMoore** [comment]
hmm can you post logs? maybe there are some crashes found in those.

so just that i understand:
1. screenshot: after loading initial savegame
2. screenshot: after a combat mission without loading
3. screenshot: after a combat mission, then saved, then loaded

was 3. with or without a game restart? my guess is without.

**Comment by st3fan21** [comment]
1. screenshot: after loading initial savegame
2. screenshot: after a combat mission without loading
3. screenshot: after a combat mission without loading, 1 min after 2.

I tryed everything, the only thing that resets the problem is restarting the game

**Comment by st3fan21** [comment]
I even tryed windowed , fullscreen, changing resolutions.

**Comment by st3fan21** [comment]
Where do i find logs?
The game works fine, no visible crashes but maybe you can find something.

**Comment by CptMoore** [comment]
logs should be in MechEngineer/log.txt and the other one I always forget

doesn't matter I hope, I have found some issues can you try 2.0.1?

**Comment by st3fan21** [comment]
Everything works well so far in 2.0.1.
And i see you also added some color codes for the non-movable parts. Very nice, and quite helpful.

**Comment by st3fan21** [comment]
You can close this thread :)
