### ISSUE TITLE
How to use Mortars

### ISSUE THREAD

**Issue by st3fan21** [BattletechModders/MechEngineer#169]
I tryed mortars on a few mechs but they always show as if they have no ammo. Any ideas?

**Comment by CptMoore** [comment]
don't really have the heavy metal dlc, so I can't test it, but I thought its an ability and you have to mount the "upgrade" not the weapon.
probably a bug that the weapon can even be mounted

**Comment by st3fan21** [comment]
Dude you have to have heavy metal, lots of new stuff. Since you ve created these mods let me send you this dlc as a gift. give me your steam id. It s the least i can do for all your work.

**Comment by CptMoore** [comment]
I already refused the dlc as gift from someone else. I was gifted the flashpoint and urban combat dlcs and I still didnt play those, so don't want stuff that has to be bought with money that I then don't play.

**Comment by st3fan21** [comment]
Well in that case i can send a small gift at least. on paypal or patreon (dont have patreon account but i can make one).

**Comment by CptMoore** [comment]
I don't really need much, I live in a high income country. but if you want to donate, you can donate to @LadyAlekto / RogueTech (Donation page is on Nexus, https://www.nexusmods.com/Core/Libs/Common/Widgets/PayPalPopUp?user=6191338 , RogueTech /lady also doesn't need it but at least the community donations are at one place )

in any case, where my suspicions correct, was the mortar a weapon and not the upgrade?

**Comment by st3fan21** [comment]
I am not sure let me post a photo. I can tell you this much, i salvaged 1 and bought 1 and they are both upgrades. you mount them on l/r torso and they should have just one shot. they do appear in the missions but their colors are faded as if they have no ammo.

**Comment by st3fan21** [comment]
![1](https://user-images.githubusercontent.com/49989588/71558479-8bdb8a00-2a5c-11ea-9c47-9e8da322b5ff.png)

**Comment by CptMoore** [comment]
maybe you should join discord and ask for someone if they have the same symptoms

battletech & mw5 modding discord:
https://discord.gg/G5J2Jvz

offiical mechengineer discord:
https://discord.gg/ChBxAB2

**Comment by CptMoore** [comment]
I think this was fixed, the issue was that mortars were crashing if a weapon wasn't mapped to a visual representation. hardpointfix part of ME doesnt do fallbacks unless they make sense (LRM->SRM ok, LRM->PPC nok).
A fix + setting was added that still creates some fallbacks, but only for mortars.
