### ISSUE TITLE
Request to add Mortars as a prefab fallback for ME fallback settings.

### ISSUE THREAD

**Issue by bloodydoves** [BattletechModders/MechEngineer#174]
Much like how artillery now is a counted prefab for fallback purposes, Shade and I were talking about future models and we'd like to have "mortar" added as a prefab fallback in MC. Can that be done?

**Comment by CptMoore** [comment]
you can always do those mapping yourself in the ME settings of your installation. Anyway I just added something like this:
```            new WeaponPrefabMapping
            { /* requested by bloodydoves */
                PrefabIdentifier= "mortar",
                HardpointCandidates = new[] {"mortar", "ac20", "uac20", "lbx20", "ac", "lbx"}
            },```
