### ISSUE TITLE
PPC, not SBD

### ISSUE THREAD

**Issue by BlazeStryker** [BattletechModders/MechEngineer#179]
I am running a mod-enhanced Hyades Rim setup and so far Mech Engineer seems to have no issues in itself. That said, the visual and audio display of PPC use is missing. I had installed the weapons sounds mod and will do so again, but I have to ask why the screechers got cloaked. (They do work, by the way, but no visuals and no sound)

Actually getting into the Mechbay, I found Heatbanks and other items provided by Hyades Rim and Battletech Enhanced were not recognized by MechEngineer.  It's a shame, really.

**Comment by CptMoore** [comment]
MechEngineer overrides mounted weapon to prefab mappings. Vanilla would select a PPC prefab when mounting a SRM, in ME it tries more sensible fallbacks by finding LRMs first. However with ME if it cant find a mapping, weapon shooting will stay silent and that would lead to missing visuals.

You can disable the hardpointfix feature from ME and the shooting sounds and visuals should be back.

**Comment by CptMoore** [comment]
Oh my explanation wasn't really good.. so here a better one:
1. vanilla maps everything somehow, so every weapon gets a visual representation. So a PPC could be mapped to SRM
2. ME does NOT map stuff that makes no sense, that's all configurable using the settings though
3. when a weapon fires that has no visual representation, it will have missing sounds and effects unfortunately

The only way to solve this is to make sure only weapons can be mounted that have a visual representation. The hardpoint fix from ME does have an option to enforce that.
