### ISSUE TITLE
Request: Extension for max possible hits detection on components

### ISSUE THREAD

**Issue by IceRaptor** [BattletechModders/MechEngineer#181]
I'm writing a new mod that is intended to represent damaged or salvaged mechs by randomly damaging components and structure. For ME components, it would be helpful to have an extension on the MechComponent that I could call to determine the maximum number of hits an item could take. This way I could prevent killing a unit before it even spawns by limiting engine or gyro hits to max - 1.

I would normally limit total hits to 1, but BloodyDoves has implemented primitive engines with 1 crit as a critical component. Being able to detect RT primitives vs. BTA primitives requires a check of total possible damage.

Thank you in advance!

**Comment by CptMoore** [comment]
get CriticalEffects custom component and then just .MaxHits
