### ISSUE TITLE
Qiurk mech in pop-up desscription

### ISSUE THREAD

**Issue by GreyW3** [BattletechModders/MechEngineer#183]
Good day.
Could you, please, bring quirk of mech to the pop-up description panel that appears above its part? This will help evaluate the significance of the mech before it is assembled. Now mech quirk are not displayed anywhere except the mechlab in refit window.
Something like this 
[![imageban](https://i2.imageban.ru/out/2020/03/13/be0868d8faa18eaf346143f27ce25c35.png)](https://imageban.ru)

**Comment by LadyAlekto** [comment]
This would be a RT issue and the RT quirks work completely different

Why are you posting a RT thing on the mechengineer git?

**Comment by GreyW3** [comment]
I apologize if I wrote to the wrong address. Also, I understand that perhaps the idea is difficult to implement. So this is just an offer.

**Comment by CptMoore** [comment]
well.. I could add bonus descriptions to mechdefs, what you say @LadyAlekto ?
actuator restrictions labels would be something I'd add to ME vanilla via those bonus descriptions

**Comment by LadyAlekto** [comment]
Actuator restrictions automatically would be awesome

Though it would need to distinguish between omni and normal restriction

I cant see how you could grab a specific fixed installed items description to auto add though

**Comment by CptMoore** [comment]
If fixed installed items are defined using the fixed equipment array from ChassisDefs then it should be very simple! I would just display the bonus description of the fixed item directly as bonus to the chassis descriptions.

**Comment by CptMoore** [comment]
arm actuator description are now auto added, text can be changed in ME settings and via ChassisDescription as part of ArmActuatorSupport custom

**Comment by CptMoore** [comment]
Adding descriptions automatically. Inter mod compatibility is done by having CC be the middle man for modifying descriptions.

**Comment by CptMoore** [comment]
if someone wants more bonusDescription support reopen this or open another issue
