### ISSUE TITLE
Engine Core Issue

### ISSUE THREAD

**Issue by TotalMeltdown** [BattletechModders/MechEngineer#187]
Unable to install some default engine cores due to weight restrictions in mechlab. 
I.E. Stalker (255) and Awesome (240). Engines don't show up in the menu due to calc of chassis tonnage? Not sure if intentional. Checked a few other mechs, looks like any assault mech that runs an engine lower than a 300 has issues in the mechlab. Mauler, Nightstar, Highlander, Stalker, Awesome, etc.

Settings.json file gets overwritten by dll if options to disable restrictions. dll throws error if file is set to read only. xD

Edit: Ran over to Smurfy's, I can slot a STD 100 in a stalker at min, and STD 160 for an Awesome. Not sure what the ratio should be since a stalker is heavier than an Awesome and you can slot a smaller engine.

**Comment by CptMoore** [comment]
There is a minimum sprint distance setting in vanilla, and ME is using that to calculate the minimum engine you have to install. I think just reducing the minimum sprint distance to 0 would allow all engine types. Dont know the exact name, but must be inside a constants json file under the streamingassets folder from ME. I also dont allow all engine ratinga anyway, only those that mech are already using. Mainly to avoid cluttering the mechlab with a huge list of engines. But there is an autofix setting I believe to allow all engine ratings to appear in the mechlab. (Note that minsprint setting mentioned before still takes precedence)

**Comment by TotalMeltdown** [comment]
Yep, changing the minSprint from 120 down to 90 solved the issue. Looks like the specific mech's movedef file that sets the chassis speed limits the engine rating as well. So dropping the minimum sprint distance inside the mechstat constants file to 90 and not 0, sets the correct ranges for mechs. 

 Testing on the Stalker and Awesome I was able to slot their default engine rating w/o being able to drop the mech below its min speed for the chassis. The Awesome was able to drop all the way down to a 200 rated engine instead of the 240 stock. So that bulky guy can get even slower if you really wanted, but the stalker's lowest engine rating is still in default. So yea, set it to 0 and you can slot anything you want, but the mech's sprint just zero's out if you select it.
