### ISSUE TITLE
infinite loading with customised base game mechs

### ISSUE THREAD

**Issue by bensonae** [BattletechModders/MechEngineer#189]
Hi guys,

Using Mech Engineer with full DLC vanilla and ME required mods. Using the skirmish mech bay to modify base game mechs, in this case the urbanmech, and have found that when trying to use these mechs in skirmish mode, the game goes into an infinite load. Attached is the debug console dumps that shows the error that occurs. This error does not occur with DLC mech chassis, like the phoenix hawk. The only requirement to throw this fault is the mech must be a base game mech, and must be a player customised variant, stock variants work just fine. There is no use of custom parts, beside what is loaded by default with Mech Engineer.

[20200703_22-24-43_LogFile.txt](https://github.com/BattletechModders/MechEngineer/files/4870000/20200703_22-24-43_LogFile.txt)
![20200703_22-24-43_Capture](https://user-images.githubusercontent.com/67792283/86474633-679d9480-bd82-11ea-9c85-72c0ee0e56d4.png)
[20200703_22-24-43_Console.txt](https://github.com/BattletechModders/MechEngineer/files/4870006/20200703_22-24-43_Console.txt)

**Comment by CptMoore** [comment]
damn, for me I dont see it crashing, can you post screenshots of your custom mechs?

I assume you are playing with modloader (not modtek)

you could maybe have some data from trying out other mods, its very hard to get rid of those (involved clearning parts of the registry, mddb a temp sqlite database in the game folder, and also could be modtek or modloader cache).

**Comment by bensonae** [comment]
Am using modtek, have cleaned out every cache i could find, including those in appdata, .modtek and the steam userdata folder. Not sure where i would have to go in my registry to clean something out. I downloaded and installed the CAB bundle off nexonmods, but it didn't do anything for me because I wasn't using the mechs/chassis, so I got rid of it.

Here is a screen shot of each of the mechs I am using. Note that these all work except the 
![20200704212848_1](https://user-images.githubusercontent.com/67792283/86512180-d17b7400-be3e-11ea-8a99-4eb45ffef9fa.jpg)
![20200704212939_1](https://user-images.githubusercontent.com/67792283/86512181-d4766480-be3e-11ea-8b7a-cf3e447d7ce1.jpg)
![20200704213016_1](https://user-images.githubusercontent.com/67792283/86512183-d5a79180-be3e-11ea-88a2-8cb60d1756e5.jpg)
![20200704213205_1](https://user-images.githubusercontent.com/67792283/86512184-d8a28200-be3e-11ea-9eae-f269afd01b98.jpg)

**Comment by CptMoore** [comment]
Interesting, can you attach the settings you are using for ME? the urbanmech is missing the armor/structure ratio enforcement thats on by default (armor front+back can't exceed together 2x structure)

I think roguetech properly deletes everything even the registry. So install it and then immediately uninstall it again. Problem is when using GOG or Steam the cloud saves also interfere so... disable those just to be sure.

Since you are using modtek, you might get lucky with using https://github.com/BattletechModders/NewSaveFolder , that mod basically redirects all saves and also registry saves to a folder in the BT installation, meaning it should be easy to delete caches from there.

**Comment by bensonae** [comment]
I did change the ME armor enforcement rule and engine size enforcement, and turned off the intro cinematics, otherwise settings are untouched. Yes, i have disabled steam cloud saves and am not logging in to the paradox servers in game, that save folder mod looks interesting though. Here is the settings.last file and settings file.

[MechEngineersettings.zip](https://github.com/BattletechModders/MechEngineer/files/4874525/MechEngineersettings.zip)

**Comment by CptMoore** [comment]
![fear](https://user-images.githubusercontent.com/39010654/86533522-17354c80-bed2-11ea-9bc4-deb9c81d61f7.png)
I could replicate your infamous "URBANMECH -COPY", but can't get it to infinity load :(

Try those means to redirect saves or clean them.

**Comment by bensonae** [comment]
Thanks Cap. I did the RT install & uninstall, no joy. Did a full uninstall and reg clean, before then reinstalling and progressively loading mods. No faults as of yet, fingers crossed. Think it might have been something in the modtek database.

**Comment by CptMoore** [comment]
*crossing fingers*

**Comment by CptMoore** [comment]
Any update on this?

**Comment by bensonae** [comment]
All good, have found that weapons can still be fired even after the mount location has been destroyed, but I think that is something different to the issue I was having. I dare say my problem has been solved.

**Comment by CptMoore** [comment]
damn, yea that sounds like interference between mods.. like earlier versions of AIM/CAC/ME/...
