### ISSUE TITLE
Gauss Rifle++ misses out on critical slot adjustment

### ISSUE THREAD

**Issue by PainGod85** [BattletechModders/MechEngineer#192]
Since the mod only checks for GR type weapons that have 5 slots before adding 2 more, the 4 slot GR++ doesn't get adjusted with its two larger versions.

**Comment by CptMoore** [comment]
I guess there is no harm in also fixing ++ variants. Don't like ++ due to it being flat improvements but Ill just add 2 slots as suggested by allowing min size 4.
