### ISSUE TITLE
Allow per-mech override of prefab mapping

### ISSUE THREAD

**Issue by spootmonkey** [BattletechModders/MechEngineer#201]
As requested post discussion on Discord: https://discord.com/channels/461969585588011008/461969585588011010/826411637195800586

**Comment by CptMoore** [comment]
## Mapping Override:

idea would be to use for each prefabIdentifier either the global settings from WeaponPrefabMappings or the chassisdef specific one.

structure would be like
```
{
  "chassisDefId": "chassis_hunchback",
  "mappings": [
    {
      "PrefabIdentifier": "lrm20",
      "HardpointCandidates": ["lrm20"]
    },
    {
      "PrefabIdentifier": "mrm40",
      "HardpointCandidates": ["srm20"]
    }
  ]
}
```

First a query looks for compatible prefab terms from the chassisDef specific one, if not found it will use the global one.
An empty hardpoint candidates array in the chassisDef specific one would allow to remove mappings.

**Comment by CptMoore** [comment]
@CMiSSioN is currently implementing something like HardpointFix as part of his CustomBundle to support quads. So I probably will not implement this and slowly phase out HardpointFix once his implementation hits the streets ;)
