### ISSUE TITLE
Engine heatsinks not counting towards heatsink capacity during tutorial

### ISSUE THREAD

**Issue by SteelShrike** [BattletechModders/MechEngineer#205]
Hello!

I'll preface this by saying I'm using MechEngineer apart from RogueTech or BTA. Been making a mod compilation built around MechEngineer for personal use through the story campaign.

It's working 99% of the time, but I noticed that it doesn't seem like the engine heatsinks are counting towards heat dissipation during the very first tutorial mission. I've tested extensively, and the Blackjack will dissipate exactly 12 points of heat, which lines up with how many external heatsinks it's carrying. But the other 21 from the 7 internal heatsinks don't appear to work. It actually renders the tutorial unwinnable because the Blackjack doesn't have the heatsink capacity to cool off and reach the Panther to complete the melee objective unless I brute force the Blackjack to have a higher base speed. After that first mission however, everything appears to work as expected again.

I understand if this would be extremely low priority, but the help would be appreciated!

**Comment by CptMoore** [comment]
I'll try it to reproduce it on my end, is the engine fully installed on the tutorial mech? core, engine, gyro, engine heat block..

**Comment by SteelShrike** [comment]
The mech used during the tutorial is just a standard BJ-1 Blackjack before they take away your jumpjets, so it shouldn't behave any differently. I had made some modifications to the items in MechEngineer so I thought maybe that was it, but I tested it with the latest version, no changes and no other mods active, and it still occurred.

I suspect it's something to do with how heavily scripted that first mission is and how it disables certain abilities until you're required to use them, but it's just a hunch.

**Comment by CptMoore** [comment]
ok just started the tutorial, moved, shot 4 MBL

init
> sourceID = EngineCoreEffect_HeatSinkCapacity_ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0, statName = HeatSinkCapacity, op = Int_Add, variant = 21
sourceID = PassiveEffect_ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0_36, statName = HeatSinkCapacity, op = Int_Add, variant = 3
sourceID = PassiveEffect_ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0_37, statName = HeatSinkCapacity, op = Int_Add, variant = 3
sourceID = PassiveEffect_ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0_38, statName = HeatSinkCapacity, op = Int_Add, variant = 3

21+3+3+3 => 30
looks alright

>2021-07-07T18:47:58 CombatLog.Heat [LOG] Mech Blackjack (ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0) gains 12 heat from firing M Laser
2021-07-07T18:47:58 CombatLog.Heat [LOG] Mech Blackjack (ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0) gains 12 heat from firing M Laser
2021-07-07T18:47:58 CombatLog.Heat [LOG] Mech Blackjack (ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0) gains 12 heat from firing M Laser
2021-07-07T18:47:58 CombatLog.Heat [LOG] Mech Blackjack (ec9d2280-ca9a-4d90-8a20-963d8a4c0a39.0) gains 12 heat from firing M Laser

4x12 -> 48
makes sense to me

> 2021-07-07T18:48:02 CombatLog.Heat [LOG] Mech Blackjack sinks 11 points of heat; result heat = 37

37 left??
-11??
what?
48-30 = 18 left

> 2021-07-07T18:48:02 CombatLog.Heat [LOG] Mech Blackjack final heat = 37 out of 100

lies!

**Comment by CptMoore** [comment]
> 2021-07-07T20:08:02 Changed stat to 21
2021-07-07T20:08:02 Changed stat to 24
2021-07-07T20:08:02 Changed stat to 27
2021-07-07T20:08:02 Changed stat to 30
2021-07-07T20:08:10 Changed stat to 11

yea someone hardcodes this to 11

**Comment by CptMoore** [comment]
> BattleTech.UI.CombatHUD.GrantBonusHeatSinksAndUnhittable

**Comment by SteelShrike** [comment]
That's VERY bizarre. The only way that makes sense from an unmodded perspective is if that number is meant to be multiplied by 3. 10 internal heatsinks by default and then the one external heatsink the BJ-1 has in the vanilla game.

If I turn off the HeatSinkCapacityStat setting in the MechEngineer Settings.json, it actually sinks the appropriate amount of heat. Obviously the rest of the game breaks then at that point.

**Comment by CptMoore** [comment]
> int num = (int)mech.TotalHeatProducedByWeapons - 45;
num = Mathf.Max(num, 0);
mech.StatCollection.Set<int>("HeatSinkCapacity", forced ? num : 0);

**Comment by CptMoore** [comment]
I fixed it by just disabling the offending code that does the StatCollection.Set .
See upcoming automated latest build.
